"""
Django settings for matting_system project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0v87g9x3jyf6zqk5h8l2m1n3o4p5r6s7t8u9v0w1x2y3z4a5b6c7d8e9f0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'uploads',
    'matting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'matting_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'matting.context_processors.unread_messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'matting_system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'


TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_URL = 'users:login'

# 更改默认语言为中文
LANGUAGE_CODE = 'zh-hans'

# SimpleUI配置
ADMIN_SITE_HEADER = '人像抠图系统管理后台'
ADMIN_SITE_TITLE = '人像抠图系统管理后台'
ADMIN_INDEX_TITLE = '欢迎使用人像抠图系统管理后台'

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 管理员菜单配置
SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['用户管理', '图像上传管理', '人像抠图管理', '系统日志', '消息与公告'],
    'menus': [
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户信息',
                    'icon': 'fas fa-user',
                    'url': '/admin/users/user/'
                }
            ]
        },
        {
            'name': '图像上传管理',
            'icon': 'fas fa-image',
            'models': [
                {
                    'name': '上传图像',
                    'icon': 'fas fa-upload',
                    'url': '/admin/uploads/uploadedimage/'
                }
            ]
        },
        {
            'name': '人像抠图管理',
            'icon': 'fas fa-cut',
            'models': [
                {
                    'name': '抠图结果',
                    'icon': 'fas fa-images',
                    'url': '/admin/matting/mattingresult/'
                }
            ]
        },
        {
            'name': '系统日志',
            'icon': 'fas fa-bug',
            'models': [
                {
                    'name': '抠图错误日志',
                    'icon': 'fas fa-exclamation-triangle',
                    'url': '/admin/matting/mattingerrorlog/'
                }
            ]
        },
        {
            'name': '消息与公告',
            'icon': 'fas fa-envelope',
            'models': [
                {
                    'name': '用户消息',
                    'icon': 'fas fa-comments',
                    'url': '/admin/matting/usermessage/'
                },
                {
                    'name': '系统公告',
                    'icon': 'fas fa-bullhorn',
                    'url': '/admin/matting/systemnotice/'
                }
            ]
        }
    ]
}

