# Generated by Django 4.2.2 on 2026-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mattingresult",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mattingresult",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
