# Generated by Django 4.2.2 on 2026-02-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
        ("matting", "0002_mattingresult_deleted_at_mattingresult_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="mattingresult",
            name="uploaded_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uploads.uploadedimage",
            ),
        ),
        migrations.AlterField(
            model_name="mattingresult",
            name="original_image",
            field=models.ImageField(blank=True, null=True, upload_to="originals/"),
        ),
        migrations.AlterField(
            model_name="mattingresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("deleted", "已删除"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
