# Generated by Django 4.2.2 on 2026-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matting", "0003_mattingresult_uploaded_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mattingresult",
            name="uploaded_image",
        ),
        migrations.AlterField(
            model_name="mattingresult",
            name="original_image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="originals/"
            ),
        ),
    ]
