# Generated by Django 4.2.2 on 2026-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matting", "0004_remove_mattingresult_uploaded_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mattingresult",
            name="model_info",
            field=models.TextField(blank=True, help_text="模型详细信息（如配置文件路径等）", null=True),
        ),
        migrations.AddField(
            model_name="mattingresult",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("default", "默认模型"),
                    ("high_quality", "高质量模型"),
                    ("lightweight", "轻量化模型"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mattingresult",
            name="original_image",
            field=models.ImageField(upload_to="originals/"),
        ),
    ]
