# Generated by Django 4.2.2 on 2026-03-11 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matting", "0005_mattingresult_model_info_mattingresult_model_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MattingErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_level",
                    models.CharField(
                        choices=[
                            ("INFO", "信息"),
                            ("WARNING", "警告"),
                            ("ERROR", "错误"),
                            ("CRITICAL", "严重错误"),
                        ],
                        default="ERROR",
                        max_length=10,
                        verbose_name="错误级别",
                    ),
                ),
                (
                    "error_category",
                    models.CharField(
                        choices=[
                            ("MODEL_LOAD", "模型加载失败"),
                            ("IMAGE_PROCESS", "图像处理失败"),
                            ("PREDICTION", "模型预测失败"),
                            ("FILE_SAVE", "文件保存失败"),
                            ("OTHER", "其他错误"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="错误类别",
                    ),
                ),
                ("error_message", models.TextField(verbose_name="错误信息")),
                (
                    "error_traceback",
                    models.TextField(blank=True, null=True, verbose_name="错误堆栈"),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="图像路径"
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="模型类型"
                    ),
                ),
                (
                    "request_params",
                    models.TextField(
                        blank=True,
                        help_text="请求参数 (JSON 格式)",
                        null=True,
                        verbose_name="请求参数",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("resolved", models.BooleanField(default=False, verbose_name="是否已解决")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="管理员备注", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解决者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "抠图错误日志",
                "verbose_name_plural": "抠图错误日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
