# Generated by Django 4.2.2 on 2026-04-01 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matting", "0007_mattingresult_background_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mattingerrorlog",
            name="notify_users",
            field=models.BooleanField(default=False, verbose_name="是否通知所有用户"),
        ),
        migrations.AddField(
            model_name="mattingerrorlog",
            name="public_notice",
            field=models.TextField(
                blank=True, help_text="公开通知内容", null=True, verbose_name="公开通知"
            ),
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("USER_TO_ADMIN", "用户发给管理员"),
                            ("ADMIN_TO_USER", "管理员回复用户"),
                        ],
                        default="USER_TO_ADMIN",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="主题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[("UNREAD", "未读"), ("READ", "已读"), ("REPLIED", "已回复")],
                        default="UNREAD",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "related_error_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="matting.mattingerrorlog",
                        verbose_name="相关错误日志",
                    ),
                ),
                (
                    "replied_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="matting.usermessage",
                        verbose_name="回复的消息",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户消息",
                "verbose_name_plural": "用户消息",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "一般公告"),
                            ("ERROR_RESOLVED", "问题已解决"),
                            ("SYSTEM_MAINTENANCE", "系统维护"),
                            ("FEATURE_UPDATE", "功能更新"),
                        ],
                        default="GENERAL",
                        max_length=30,
                        verbose_name="公告类型",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
                (
                    "related_error_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="matting.mattingerrorlog",
                        verbose_name="相关错误日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统公告",
                "verbose_name_plural": "系统公告",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
