# Generated by Django 4.2.2 on 2026-04-01 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matting", "0008_mattingerrorlog_notify_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送者",
            ),
        ),
    ]
